config/routes.rb
Drawbridge::Application.routes.draw do

  resources :authorizations
  resources :chat_rooms
  resources :messages

  namespace :chat_room do
    resource :history
  end

  root :to => 'chat_rooms#index'

end

app/models/chat_room.rb
# class ChatRoom < ActiveRecord::Base
#   # attr_accessible :title, :body
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  
end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
end

app/controllers/chat_room_histories_controller.rb
class ChatRoomHistoriesController < ApplicationController

  def show
    @chat_room = ChatRoom.find_by_id(params[:format])
    @messages = @chat_room.messages
  end

end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController

  def index
    @chat_rooms = ChatRoom.all
  end

  def new
  end

  def create
    ChatRoom.create(params)
    redirect_to chat_rooms_path
  end

  def show
    @chat_room = ChatRoom.find_by_id(params[:id])
    @messages = @chat_room.messages
    count = @messages.try(:count)
    if count
      @messages = @messages[count-6..count-1]
    end
    gon.chat_room = @chat_room
  end

  private

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    Message.create(params)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def logged_in?
    if cookies["uid"]
      true
    else
      false
    end
  end

  def current_user
    { id: cookies["uid"], user_name: cookies["user_name"] }
  end

    # responses = JSON.parse(@chat_client.get('chat_rooms').body)
    # @chat_rooms = []
    # responses.each do |response|
    #   @chat_rooms << {id: response["chat_room"]["id"], title: response["chat_room"]["title"]}
    # end
    # @chat_rooms

end

app/helpers/authorizations_helper.rb
module AuthorizationsHelper
end

app/helpers/chat_room/histories_helper.rb
module ChatRoom::HistoriesHelper
end

app/helpers/chat_room_histories_helper.rb
module ChatRoomHistoriesHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper

  def convert_time(time)

  end

  # Helper Methods to use 'till data is available

  def temp_count
    @count = rand(0..10)
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/authorizations/index.html.erb
<h2>Authorization Check</h2>

<p>The cookie says:</p>
<p><i>Insert cookie information here</i><p>

app/views/chat_rooms/_chat_room_list.html.erb
<table class="table span8">
  <tr>
    <td><h4>Room Title</h4></td>
  </tr>
  <% @chat_rooms.each do |room| %>
    <tr>
      <td><strong><%= link_to room.title, chat_room_path(room.id) %></strong></td>
    </tr>
  <% end %>
</table> 

app/views/chat_rooms/_message.html.erb
<div class="row">
  <div class="span1">
    <p><%= message.user_name %></p>
  </div>
  <div class="span4">
    <p><%= message.content %></p>
  </div>
</div>
<hr />

app/views/chat_rooms/_messages.html.erb
<div class="row span6">
  <div class="row">
    <div class="span1">
      <h3>From</h3>
    </div>
    <div id="message-head" class="span3">
      <h3>Message</h3>
    </div>
    <div class="span2"><a class="btn btn-danger pull-right" data-toggle="modal" href="#historyModal">History</a></div>
  </div>

  <div class="row">
    <div class="span6 adminmsg">
      <p>Welcome to the <%= @chat_room.title %> campaign, <%= current_user[:user_name] %>. Please post your comments below. Remember they will be included in the campaign record!</p>
    </div>
  </div>

  <div id="messages" style="height:300px; overflow:scroll;">
    <% if @messages %>
      <% @messages.each do |message| %>
        <%= render partial: "message", locals: { message: message } %>
      <% end %>
    <% else %>
      <div class="row">
        <div class="span1">
          <p></p>
        </div>
        <div class="span4">
          <p>There are no posts in this campaign yet. Be the first!</p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/chat_rooms/_modal_email.html.erb
<div class="modal hide" id="emailModal">
  <div class="modal-header">
    <h3>Posting to <%= @chat_room.title %> by email:</h3>
    <button type="button" class="close" data-dismiss="modal">x</button>
  </div>
  <div class="modal-body">
    <p>Send an email to</p>
    <p class="well"><a href="mailto:conquerchat+<%= @chat_room.id %>@gmail.com">conquerchat+<%= @chat_room.id %>@gmail.com</a></p>
    <p>Your name, the subject and body of the email will be included in the post.</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn btn-inverse" data-dismiss="modal">Close</a>
  </div>
</div>

app/views/chat_rooms/_modal_github.html.erb
<div class="modal hide" id="githubModal">
  <div class="modal-header">
    <h3>Linking <%= @chat_room.title %> to a Github repo:</h3>
    <button type="button" class="close" data-dismiss="modal">x</button>
  </div>
  <div class="modal-body">
    <p>To link this chat room to a private repo you will need this Github commit hook:</p>
    <p class="well">http://conquerapp.com/github_messages?id=<%= @chat_room.id %></p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
  </div>
</div>

app/views/chat_rooms/_modal_history.html.erb
<div class="modal hide" id="historyModal">
  <div class="modal-header">
    <h3>Chat history for the <%= @chat_room.title %> campaign:</h3>
    <button type="button" class="close" data-dismiss="modal">x</button>
  </div>
  <div class="modal-body">
    <% if @chat_room.messages %>
      <% @chat_room.messages.each do |message| %>
        <%= render partial: "chat_rooms/message", locals: { message: message } %>
      <% end %>
    <% else %>
      <div class="row">
        <div class="span1">
          <p></p>
        </div>
        <div class="span6">
          <p>There is no message history for this room.</p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
  </div>
</div>

app/views/chat_rooms/_new_message_form.html.erb
<div id="message-post" class="span12">
  <%= form_tag(messages_path, method: "post", class: "form-inline", :remote => true, id: "new_message_form") do %>
    <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
    <%= hidden_field_tag 'user_id', current_user[:id] %>
    <%= hidden_field_tag 'user_name', current_user[:user_name] %>
    <%= text_field_tag(:content) %>
    <%= submit_tag("New Communique") %>
  <% end %>
</div>

app/views/chat_rooms/_sidebar.html.erb
<div class="row span2 well">
  <h3>Room Information</h3>
  <p>
  <a class="btn btn-danger" data-toggle="modal" href="#emailModal"><%= image_tag 'icons/mailV1.png' %> Post via Email</a></p>
  <a class="btn btn-danger" data-toggle="modal" href="#githubModal"><%= image_tag 'icons/octocatV1.png' %> Link to Github</a>
  <div>
</div>
</div>

app/views/chat_rooms/index.html.erb
<%= render 'shared/castle_frame' %>

<div class="offset1 span9" style="background-color:rgb(255, 255, 255); padding-bottom:20px;">
  <% if logged_in? %>

    <div class="span8">
      <h2 class="page_title">Castle <small>All Campaigns</small><%= link_to "Create a new chat room", new_chat_room_path, class: "btn btn-inverse pull-right" %></h2>
      
    </div>
      
    <% if @chat_rooms != [] %>
      <%= render partial: "chat_room_list" %>
    <% else %>
      <p>There are no chat rooms available.</p>
    <% end %>
  <% else %>
    <%= render "/shared/visitor_landing" %>
  <% end %>
</div>

app/views/chat_rooms/new.html.erb
<%= render 'shared/castle_frame' %>

<div class="offset1 span9" style="background-color:rgb(255, 255, 255); padding-bottom:20px;">
  <% if logged_in? %>

    <h2>Create a new chat room</h2>

    <%= form_tag(chat_rooms_path, method: "post") do %>
      <%= hidden_field_tag(:user_id, current_user[:id]) %> 
      <%= label_tag(:title, "Room Name:") %>
      <%= text_field_tag(:title) %>
      <%= label_tag(:privacy, "Private Campaign?") %>
      <%= check_box_tag(:privacy) %>
      <%= submit_tag("Create") %>
    <% end %>

  <% else %>
    <%= render "/shared/visitor_landing" %>
  <% end %>
</div>

app/views/chat_rooms/show.html.erb
<%= render "shared/short_castle_frame" %>

<div class="offset1 span9" style="background-color:rgb(255, 255, 255); padding-bottom:20px;">
  <% if logged_in? %>

    <div class="row span7">
      <h2 class="page_title"><%= @chat_room.title %></h2>
    </div>
    <%= render "messages" %>
    <%= render "sidebar" %>
    <%= render "new_message_form" %>

    <%= render "modal_email" %>
    <%= render "modal_github" %>
    <%= render "modal_history" %>

  <% else %>
      <%= render "/shared/visitor_landing" %>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <div class="offset1 span9">
        <a class="brand" href="#">Castle</a>
        <ul class = "nav pull-right">
          <% if logged_in? %>
            <li class="divider-vertical"></li>
            <li class="">
              <%= link_to "Lobby", chat_rooms_path %>
            </li>
            <li class="divider-vertical"></li>
            <li>
              <%= link_to "Logout", "/auth/logout" %>
            </li>

          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Castle - The Conquer App</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= include_gon %>
  <%= javascript_include_tag "http://conquerapp.com:9000/faye.js", "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render "/layouts/navbar" %>
  <div class="container">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/layouts/backup_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Drawbridge</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= include_gon %>
  <%= javascript_include_tag "http://fallinggarden.com:9000/faye.js", "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render "/layouts/navbar" %>
  <div class="container-fluid">
    <div class="row-fluid">
      <% if logged_in? %>
        <%= yield %>
      <% else %>
        <%= render "/shared/visitor_landing" %>
      <% end %>
    
    </div>
  </div>

</body>
</html>

app/views/shared/_castle_frame.html.erb
<div class="span9 offset1 castleHead">
  &nbsp;
</div>
<div class="span9 offset1 castleDiv">&nbsp;</div>

app/views/shared/_short_castle_frame.html.erb
<div class="span9 offset1 castleHead" style="height:130px;background-position:top;">&nbsp;</div>
<div class="span9 offset1 castleDiv">&nbsp;</div>

app/views/shared/_visitor_landing.html.erb
<div class="span8">
  <header class="jumbotron">
    <h1>Castle<small> Conquer your app</small><%= link_to "Login Now", '/auth/google', class: "btn btn-danger pull-right", :confirm => "Your domain must be on the whitelist to log in. Please use your @hungrymachine.com email to log in." %></h1>
  </header>
  <div class="row">
    <div class="span8">
      <p class="teaser">Castle keeps the definitive record of your application's development from inception to completion.<br />From Github commits to conversations among your team, everything is saved in an easy-to-read log for future reference.</p>
    </div>
    <div class="span4">
      <h3>Security</h3>
      <p>With Castle, you own the server - no third party. All data is stored on your system, entirely in your control. You decide who can come over the drawbridge.</p>
    </div>
    <div class="span4">
      <h3>Modularity</h3>
      <p>Castle is designed to grow with you. It works for companies with just one app and for large firms handling thousands of services in a single page load.</p>
    </div>
    <div class="offset2 span8" style="margin-top:1em;">
      <h2><span style="text-align:center; color:#9b0000;">Get Castle. Conquer your app.</span></h2>
    </div>
  </class>
</div>